//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

final class ___VARIABLE_moduleName___ViewController: UIViewController {
    // MARK: - Properties
    private let mainView = ___VARIABLE_moduleName___View()
    private let viewModel: ___VARIABLE_moduleName___ViewModel
    
    // MARK: - Init
    init(viewModel: ___VARIABLE_moduleName___ViewModel) {
        self.viewModel = viewModel
        super.init(nibName: nil, bundle: nil)
    }
    
    required init?(coder: NSCoder) {
        fatalError("Not implemented")
    }
    
    // MARK: - Lifecycle
    override func loadView() {
        super.loadView()
        view = mainView
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
    }
}

// MARK: - Public methods
extension ___VARIABLE_moduleName___ViewController {
    
}

// MARK: - Private methods
private extension ___VARIABLE_moduleName___ViewController {
    
}

