//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation

struct ___VARIABLE_moduleName___Model {
    // MARK: - Properties
    
    // MARK: - Init
    init() {
        
    }
}

// MARK: - Public methods
extension ___VARIABLE_moduleName___ViewModel {
    
}

// MARK: - Private methods
private extension ___VARIABLE_moduleName___Model {
    
}
