//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

final class ___VARIABLE_moduleName___View: UIView {
    // MARK: - Properties
    private lazy var title = UILabel()
    
    // MARK: - Initi
    override init(frame: CGRect) {
        super.init(frame: frame)
        setupViews()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setupViews()
    }
}

// MARK: - Public methods
extension ___VARIABLE_moduleName___View {
    func updateView(with model: ___VARIABLE_moduleName___Model) {
        
    }
}

// MARK: - Private methods
private extension ___VARIABLE_moduleName___View {
    func setupViews() {
        setupView()
    }
    
    func setupView() {
        
    }
}

