//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright (c) ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import Foundation
import UIKit

final class ___VARIABLE_moduleName___Coordinator: Coordinator {
    // MARK: - Properties
    private let navigationController: UINavigationController?
    
    // MARK: - Init
    init(navigationController: UINavigationController? = UINavigationController()) {
        self.navigationController = navigationController
    }
}

// MARK: - Public methods
extension ___VARIABLE_moduleName___Coordinator {
    func start() {
        show___VARIABLE_moduleName___ViewController()
    }
}

// MARK: - Private methods
private extension ___VARIABLE_moduleName___Coordinator {
    func show___VARIABLE_moduleName___ViewController() {
        let viewModel = ___VARIABLE_moduleName___ViewModel()
        let viewController = ___VARIABLE_moduleName___ViewController(viewModel: viewModel)
        navigationController?.viewControllers = [viewController]
    }
}
